{
    "swagger" : "2.0",
    "info" : {
      "description" : "This is a simple API",
      "version" : "1.0.0",
      "title" : "Swagger node_mp",
      "termsOfService" : "http://swagger.io/terms/",
      "contact" : {
        "email" : "apiteam@swagger.io"
      },
      "license" : {
        "name" : "Apache 2.0",
        "url" : "http://www.apache.org/licenses/LICENSE-2.0.html"
      }
    },
    "host" : "virtserver.swaggerhub.com",
    "basePath" : "/JS_S/nj_mp/1.0.0",
    "tags" : [ {
      "name" : "city",
      "description" : "Everything about cities",
      "externalDocs" : {
        "description" : "Find out more",
        "url" : "http://swagger.io"
      }
    }, {
      "name" : "product",
      "description" : "Everything about products"
    }, {
      "name" : "user",
      "description" : "Everything about users",
      "externalDocs" : {
        "description" : "Find out more about our store",
        "url" : "http://swagger.io"
      }
    } ],
    "schemes" : [ "https", "http" ],
    "paths" : {
      "/api/products" : {
        "get" : {
          "tags" : [ "product" ],
          "summary" : "Finds Products by status",
          "description" : "Multiple status values can be provided with comma separated strings",
          "operationId" : "findProductsByStatus",
          "produces" : [ "application/json", "application/xml" ],
          "parameters" : [ {
            "name" : "status",
            "in" : "query",
            "description" : "Status values that need to be considered for filter",
            "required" : true,
            "type" : "array",
            "items" : {
              "type" : "string",
              "enum" : [ "available", "pending", "sold" ],
              "default" : "available"
            },
            "collectionFormat" : "multi"
          } ],
          "responses" : {
            "200" : {
              "description" : "successful operation",
              "schema" : {
                "type" : "array",
                "items" : {
                  "$ref" : "#/models/productShema"
                }
              }
            },
            "400" : {
              "description" : "Invalid status value"
            }
          },
          "security" : [ {
            "productstore_auth" : [ "write:products", "read:products" ]
          } ]
        },
        "post" : {
          "tags" : [ "products" ],
          "summary" : "Add a new product to the store(list of products)",
          "operationId" : "addProduct",
          "consumes" : [ "application/json", "application/xml" ],
          "produces" : [ "application/json", "application/xml" ],
          "parameters" : [ {
            "in" : "body",
            "name" : "body",
            "description" : "Product that needs to be added to the store",
            "required" : true,
            "schema" : {
              "$ref" : "#/models/productShema"
            }
          } ],
          "responses" : {
            "405" : {
              "description" : "Invalid input"
            }
          },
          "security" : [ {
            "productstore_auth" : [ "write:products", "read:product" ]
          } ]
        },
        "put" : {
          "tags" : [ "product" ],
          "summary" : "Update an existing product",
          "operationId" : "updateProduct",
          "consumes" : [ "application/json", "application/xml" ],
          "produces" : [ "application/json", "application/xml" ],
          "parameters" : [ {
            "in" : "body",
            "name" : "body",
            "description" : "Product object that needs to be added to the store",
            "required" : true,
            "schema" : {
              "$ref" : "#/models/productShema"
            }
          } ],
          "responses" : {
            "400" : {
              "description" : "Invalid ID supplied"
            },
            "404" : {
              "description" : "Product not found"
            },
            "405" : {
              "description" : "Validation exception"
            }
          },
          "security" : [ {
            "petstore_auth" : [ "write:products", "read:products" ]
          } ]
        }
      },
      "/api/products/{productId}" : {
        "get" : {
          "tags" : [ "product" ],
          "summary" : "Find product by ID",
          "description" : "Returns a single product",
          "operationId" : "getProductById",
          "produces" : [ "application/json", "application/xml" ],
          "parameters" : [ {
            "name" : "productId",
            "in" : "path",
            "description" : "ID of product to return",
            "required" : true,
            "type" : "integer",
            "format" : "int64"
          } ],
          "responses" : {
            "200" : {
              "description" : "successful operation",
              "schema" : {
                "$ref" : "#/models/productShema"
              }
            },
            "400" : {
              "description" : "Invalid ID supplied"
            },
            "404" : {
              "description" : "Product not found"
            }
          },
          "security" : [ {
            "api_key" : [ ]
          } ]
        },
        "delete" : {
          "tags" : [ "product" ],
          "summary" : "Deletes a product",
          "operationId" : "deleteProduct",
          "produces" : [ "application/json", "application/xml" ],
          "parameters" : [ {
            "name" : "api_key",
            "in" : "header",
            "required" : false,
            "type" : "string"
          }, {
            "name" : "productId",
            "in" : "path",
            "description" : "Product id to delete",
            "required" : true,
            "type" : "integer",
            "format" : "int64"
          } ],
          "responses" : {
            "400" : {
              "description" : "Invalid ID supplied"
            },
            "404" : {
              "description" : "Product not found"
            }
          },
          "security" : [ {
            "petstore_auth" : [ "write:products", "read:product" ]
          } ]
        }
      },
      "/api/cities" : {
        "get" : {
          "tags" : [ "store" ],
          "summary" : "Returns pet inventories by status",
          "description" : "Returns a map of status codes to quantities",
          "operationId" : "getInventory",
          "produces" : [ "application/json" ],
          "parameters" : [ ],
          "responses" : {
            "200" : {
              "description" : "successful operation",
              "schema" : {
                "type" : "object",
                "additionalProperties" : {
                  "type" : "integer",
                  "format" : "int32"
                }
              }
            }
          },
          "security" : [ {
            "api_key" : [ ]
          } ]
        }
      },
      "/api/cities/{cityId}" : {
        "get" : {
          "tags" : [ "store" ],
          "summary" : "Find purchase order by ID",
          "description" : "For valid response try integer IDs with value >= 1 and <= 10.\\ \\ Other values will generated exceptions",
          "operationId" : "getOrderById",
          "produces" : [ "application/json", "application/xml" ],
          "parameters" : [ {
            "name" : "orderId",
            "in" : "path",
            "description" : "ID of pet that needs to be fetched",
            "required" : true,
            "type" : "integer",
            "maximum" : 10.0,
            "minimum" : 1,
            "format" : "int64"
          } ],
          "responses" : {
            "200" : {
              "description" : "successful operation",
              "schema" : {
                "$ref" : "#/definitions/Order"
              }
            },
            "400" : {
              "description" : "Invalid ID supplied"
            },
            "404" : {
              "description" : "Order not found"
            }
          }
        },
        "delete" : {
          "tags" : [ "store" ],
          "summary" : "Delete purchase order by ID",
          "description" : "For valid response try integer IDs with positive integer value.\\ \\ Negative or non-integer values will generate API errors",
          "operationId" : "deleteOrder",
          "produces" : [ "application/json", "application/xml" ],
          "parameters" : [ {
            "name" : "orderId",
            "in" : "path",
            "description" : "ID of the order that needs to be deleted",
            "required" : true,
            "type" : "integer",
            "minimum" : 1,
            "format" : "int64"
          } ],
          "responses" : {
            "400" : {
              "description" : "Invalid ID supplied"
            },
            "404" : {
              "description" : "Order not found"
            }
          }
        }
      },
      "/api/users" : {
        "post" : {
          "tags" : [ "user" ],
          "summary" : "Create user",
          "description" : "This can only be done by the logged in user.",
          "operationId" : "createUser",
          "produces" : [ "application/json", "application/xml" ],
          "parameters" : [ {
            "in" : "body",
            "name" : "body",
            "description" : "Created user object",
            "required" : true,
            "schema" : {
              "$ref" : "#/definitions/User"
            }
          } ],
          "responses" : {
            "default" : {
              "description" : "successful operation"
            }
          }
        }
      },
      "/api/users/{userId}" : {
        "get" : {
          "tags" : [ "user" ],
          "summary" : "Get user by user name",
          "operationId" : "getUserByName",
          "produces" : [ "application/json", "application/xml" ],
          "parameters" : [ {
            "name" : "username",
            "in" : "path",
            "description" : "The name that needs to be fetched. Use user1 for testing.",
            "required" : true,
            "type" : "string"
          } ],
          "responses" : {
            "200" : {
              "description" : "successful operation",
              "schema" : {
                "$ref" : "#/definitions/User"
              }
            },
            "400" : {
              "description" : "Invalid username supplied"
            },
            "404" : {
              "description" : "User not found"
            }
          }
        },
        "put" : {
          "tags" : [ "user" ],
          "summary" : "Updated user",
          "description" : "This can only be done by the logged in user.",
          "operationId" : "updateUser",
          "produces" : [ "application/json", "application/xml" ],
          "parameters" : [ {
            "name" : "username",
            "in" : "path",
            "description" : "name that need to be updated",
            "required" : true,
            "type" : "string"
          }, {
            "in" : "body",
            "name" : "body",
            "description" : "Updated user object",
            "required" : true,
            "schema" : {
              "$ref" : "#/definitions/User"
            }
          } ],
          "responses" : {
            "400" : {
              "description" : "Invalid user supplied"
            },
            "404" : {
              "description" : "User not found"
            }
          }
        },
        "delete" : {
          "tags" : [ "user" ],
          "summary" : "Delete user",
          "description" : "This can only be done by the logged in user.",
          "operationId" : "deleteUser",
          "produces" : [ "application/json", "application/xml" ],
          "parameters" : [ {
            "name" : "username",
            "in" : "path",
            "description" : "The name that needs to be deleted",
            "required" : true,
            "type" : "string"
          } ],
          "responses" : {
            "400" : {
              "description" : "Invalid username supplied"
            },
            "404" : {
              "description" : "User not found"
            }
          }
        }
      }
    },
    "securityDefinitions" : {
      "petstore_auth" : {
        "type" : "oauth2",
        "authorizationUrl" : "http://petstore.swagger.io/oauth/dialog",
        "flow" : "implicit",
        "scopes" : {
          "write:pets" : "modify pets in your account",
          "read:pets" : "read your pets"
        }
      },
      "api_key" : {
        "type" : "apiKey",
        "name" : "api_key",
        "in" : "header"
      }
    },
    "definitions" : {
      "Order" : {
        "type" : "object",
        "properties" : {
          "id" : {
            "type" : "integer",
            "format" : "int64"
          },
          "petId" : {
            "type" : "integer",
            "format" : "int64"
          },
          "quantity" : {
            "type" : "integer",
            "format" : "int32"
          },
          "shipDate" : {
            "type" : "string",
            "format" : "date-time"
          },
          "status" : {
            "type" : "string",
            "description" : "Order Status",
            "enum" : [ "placed", "approved", "delivered" ]
          },
          "complete" : {
            "type" : "boolean",
            "default" : false
          }
        },
        "example" : {
          "petId" : 6,
          "quantity" : 1,
          "id" : 0,
          "shipDate" : "2000-01-23T04:56:07.000+00:00",
          "complete" : false,
          "status" : "placed"
        },
        "xml" : {
          "name" : "Order"
        }
      },
      "Category" : {
        "type" : "object",
        "properties" : {
          "id" : {
            "type" : "integer",
            "format" : "int64"
          },
          "name" : {
            "type" : "string"
          }
        },
        "example" : {
          "name" : "name",
          "id" : 6
        },
        "xml" : {
          "name" : "Category"
        }
      },
      "User" : {
        "type" : "object",
        "properties" : {
          "id" : {
            "type" : "integer",
            "format" : "int64"
          },
          "username" : {
            "type" : "string"
          },
          "firstName" : {
            "type" : "string"
          },
          "lastName" : {
            "type" : "string"
          },
          "email" : {
            "type" : "string"
          },
          "password" : {
            "type" : "string"
          },
          "phone" : {
            "type" : "string"
          },
          "userStatus" : {
            "type" : "integer",
            "format" : "int32",
            "description" : "User Status"
          }
        },
        "example" : {
          "firstName" : "firstName",
          "lastName" : "lastName",
          "password" : "password",
          "userStatus" : 6,
          "phone" : "phone",
          "id" : 0,
          "email" : "email",
          "username" : "username"
        },
        "xml" : {
          "name" : "User"
        }
      },
      "Tag" : {
        "type" : "object",
        "properties" : {
          "id" : {
            "type" : "integer",
            "format" : "int64"
          },
          "name" : {
            "type" : "string"
          }
        },
        "example" : {
          "name" : "name",
          "id" : 1
        },
        "xml" : {
          "name" : "Tag"
        }
      },
      "Pet" : {
        "type" : "object",
        "required" : [ "name", "photoUrls" ],
        "properties" : {
          "id" : {
            "type" : "integer",
            "format" : "int64"
          },
          "category" : {
            "$ref" : "#/definitions/Category"
          },
          "name" : {
            "type" : "string",
            "example" : "doggie"
          },
          "photoUrls" : {
            "type" : "array",
            "xml" : {
              "name" : "photoUrl",
              "wrapped" : true
            },
            "items" : {
              "type" : "string"
            }
          },
          "tags" : {
            "type" : "array",
            "xml" : {
              "name" : "tag",
              "wrapped" : true
            },
            "items" : {
              "$ref" : "#/definitions/Tag"
            }
          },
          "status" : {
            "type" : "string",
            "description" : "pet status in the store",
            "enum" : [ "available", "pending", "sold" ]
          }
        },
        "example" : {
          "photoUrls" : [ "photoUrls", "photoUrls" ],
          "name" : "doggie",
          "id" : 0,
          "category" : {
            "name" : "name",
            "id" : 6
          },
          "tags" : [ {
            "name" : "name",
            "id" : 1
          }, {
            "name" : "name",
            "id" : 1
          } ],
          "status" : "available"
        },
        "xml" : {
          "name" : "Pet"
        }
      },
      "ApiResponse" : {
        "type" : "object",
        "properties" : {
          "code" : {
            "type" : "integer",
            "format" : "int32"
          },
          "type" : {
            "type" : "string"
          },
          "message" : {
            "type" : "string"
          }
        },
        "example" : {
          "code" : 0,
          "type" : "type",
          "message" : "message"
        }
      }
    },
    "externalDocs" : {
      "description" : "Find out more about Swagger",
      "url" : "http://swagger.io"
    }
  }